on:
  workflow_call:

jobs:
  bvt-appleclang:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4

    - name: install meson
      run: pipx install meson

    - name: check compiler versions
      run: |
        cc --version
        xcodebuild -version

    - name: build and run test with AppleClang on cmake
      run: |
        cmake -B build-cmake -GNinja -DCMAKE_CXX_STANDARD=23 -DCMAKE_BUILD_TYPE=Release -DPROXY_BUILD_MODULES=FALSE
        cmake --build build-cmake -j
        ctest --test-dir build-cmake -j
        mkdir build-cmake/drop
        bash ./tools/dump_build_env.sh c++ build-cmake/drop/env-info.json

    - name: build and run test with AppleClang on meson
      run: |
        meson setup build-meson --buildtype=release -Dtests=enabled -Dbenchmarks=enabled --force-fallback-for=fmt
        meson test -C build-meson
        meson test -C build-meson --benchmark --test-args=--benchmark_list_tests=true

    - name: run benchmarks
      run: build-cmake/benchmarks/msft_proxy_benchmarks --benchmark_min_warmup_time=0.1 --benchmark_min_time=0.1s --benchmark_repetitions=30 --benchmark_enable_random_interleaving=true --benchmark_report_aggregates_only=true --benchmark_format=json > build-cmake/drop/benchmarking-results.json

    - name: archive benchmarking results
      uses: actions/upload-artifact@v4
      with:
        name: drop-appleclang
        path: build-cmake/drop/
