on:
  workflow_call:

jobs:
  bvt-oneapi:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: install meson
      run: pipx install meson

    - name: install libc++
      run: |
        sudo apt-get install -y libc++-19-dev libc++abi-19-dev
        cat <<'EOF' >> "$GITHUB_ENV"
        CXXFLAGS=-stdlib=libc++
        EOF

    - name: install intel oneAPI
      run: |
        sudo wget -qO /etc/apt/trusted.gpg.d/intel-oneapi.asc https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/intel-oneapi.list
        sudo apt update
        sudo apt install -y intel-oneapi-compiler-dpcpp-cpp
        source /opt/intel/oneapi/setvars.sh
        cat<<-EOF >> "$GITHUB_ENV"
        PATH=$PATH
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH
        CC=$(which icx)
        CXX=$(which icpx)
        EOF

    - name: check compiler version
      run: |
        "$CXX" --version

    - name: build and run test with oneapi on cmake
      run: |
        cmake -B build-cmake -GNinja -DCMAKE_CXX_STANDARD=23 -DCMAKE_BUILD_TYPE=Release
        cmake --build build-cmake -j
        ctest --test-dir build-cmake -j
        mkdir build-cmake/drop
        bash ./tools/dump_build_env.sh "$CXX" build-cmake/drop/env-info.json

    - name: build and run test with oneapi on meson
      run: |
        meson setup build-meson --buildtype=release -Dtests=enabled -Dbenchmarks=enabled --force-fallback-for=fmt
        meson test -C build-meson
        meson test -C build-meson --benchmark --test-args=--benchmark_list_tests=true

    - name: run benchmarks
      run: build-cmake/benchmarks/msft_proxy_benchmarks --benchmark_min_warmup_time=0.1 --benchmark_min_time=0.1s --benchmark_repetitions=30 --benchmark_enable_random_interleaving=true --benchmark_report_aggregates_only=true --benchmark_format=json > build-cmake/drop/benchmarking-results.json

    - name: archive benchmarking results
      uses: actions/upload-artifact@v4
      with:
        name: drop-oneapi
        path: build-cmake/drop/
