on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false

jobs:
  bvt-appleclang:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    - name: check compiler versions
      run: |
        clang --version
        xcodebuild -version

    - name: build and run test with AppleClang
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j
        ctest --test-dir build -j

    - name: run benchmarks
      run: |
        ./build/benchmarks/msft_proxy_benchmarks --benchmark_repetitions=100 --benchmark_report_aggregates_only=true --benchmark_min_time=0.1 --benchmark_enable_random_interleaving=true
