on:
  workflow_call:

jobs:
  meson:
    runs-on: ${{ matrix.platform }}
    name: meson on ${{ matrix.platform }} (${{ matrix.mode.name }})
    strategy:
      fail-fast: false
      matrix:
        mode:
          - name: default
            args: -Dtests=enabled -Dbenchmarks=disabled
            extra_envs: {}

          # Alternative compiler setups
          - name: gcc
            args: -Dtests=enabled -Dbenchmarks=disabled
            extra_envs:
              CC: gcc
              CXX: g++
          - name: clang
            args: -Dtests=enabled -Dbenchmarks=disabled
            extra_envs:
              CC: clang
              CXX: clang++

          - name: sanitize
            args: >-
              -Dtests=enabled -Dbenchmarks=disabled "-Db_sanitize=address,undefined"
            extra_envs: {}

          # This is for MSVC, which only supports AddressSanitizer.
          # https://learn.microsoft.com/en-us/cpp/sanitizers/
          - name: sanitize+asanonly
            args: -Dtests=enabled -Dbenchmarks=disabled -Db_sanitize=address
            extra_envs:
              ASAN_OPTIONS: report_globals=0:halt_on_error=1:abort_on_error=1:print_summary=1

          - name: clang+sanitize
            args: >-
              -Dtests=enabled -Dbenchmarks=disabled -Db_lundef=false "-Db_sanitize=address,undefined"
            extra_envs:
              CC: clang
              CXX: clang++

          # default clang on GitHub hosted runners is from MSYS2.
          # Use Visual Studio supplied clang-cl instead.
          - name: clang-cl
            args: >-
              -Dtests=enabled -Dbenchmarks=disabled
            extra_envs:
              CC: clang-cl
              CXX: clang-cl
          - name: clang-cl+sanitize
            args: >-
              -Dtests=enabled -Dbenchmarks=disabled "-Db_sanitize=address,undefined"
            extra_envs:
              CC: clang-cl
              CXX: clang-cl
        platform:
          - ubuntu-24.04
          - windows-2025
          - macos-15

        exclude:
          # clang-cl only makes sense on windows.
          - platform: ubuntu-24.04
            mode:
              name: clang-cl
          - platform: macos-15
            mode:
              name: clang-cl
          - platform: ubuntu-24.04
            mode:
              name: clang-cl+sanitize
          - platform: macos-15
            mode:
              name: clang-cl+sanitize

          # FIXME: clang-cl is currently broken:
          # https://github.com/llvm/llvm-project/issues/143245
          - platform: windows-2025
            mode:
              name: clang-cl
          - platform: windows-2025
            mode:
              name: clang-cl+sanitize

          # Use clang-cl instead of MSYS2 clang.
          #
          # we already tested clang+sanitize on linux,
          # if this doesn't work, it should be an issue for MSYS2 team to consider.
          - platform: windows-2025
            mode:
              name: clang
          - platform: windows-2025
            mode:
              name: clang+sanitize

          # MSVC-only sanitizers
          - platform: ubuntu-24.04
            mode:
              name: sanitize+asanonly
          - platform: macos-15
            mode:
              name: sanitize+asanonly
          - platform: windows-2025
            mode:
              name: sanitize

          # clang is the default on macos
          # also gcc is an alias to clang
          - platform: macos-15
            mode:
              name: clang
          - platform: macos-15
            mode:
              name: gcc

          # gcc is the default on linux
          - platform: ubuntu-24.04
            mode:
              name: gcc

          # MinGW is not officially tested
          - platform: windows-2025
            mode:
              name: gcc

          # only run sanitizer tests on linux
          #
          # gcc/clang's codegen shouldn't massively change across platforms,
          # and linux supports most of the sanitizers.
          - platform: macos-15
            mode:
              name: clang+sanitize
          - platform: macos-15
            mode:
              name: sanitize

    steps:
      - name: Setup meson
        run: |
          pipx install meson ninja
      - name: Checkout
        uses: actions/checkout@v4
      - name: Activate MSVC and Configure
        if: ${{ matrix.platform == 'windows-2025' }}
        env: ${{ matrix.mode.extra_envs }}
        run: |
          meson setup build --buildtype=release ${{ matrix.mode.args }} --vsenv
      - name: Configure
        if: ${{ matrix.platform != 'windows-2025' }}
        env: ${{ matrix.mode.extra_envs }}
        run: |
          meson setup build --buildtype=release ${{ matrix.mode.args }}
      - name: Build
        run: |
          meson compile -C build
          meson compile -C build msft_proxy_tests examples

      - name: Run tests
        env: ${{ matrix.mode.extra_envs }}
        run: |
          meson test -C build --timeout-multiplier 5 --print-errorlogs
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ${{ matrix.platform }}-${{ matrix.mode.name }}-logs
          path: build/meson-logs
